from pathlib import Path
indent_base = "                                "

def line(level: int, text: str) -> str:
    return indent_base + "    " * level + text

lines = [
    line(0, "{stockConferenceHistory.length === 0 ? ("),
    line(1, '<div className="text-center py-12 text-sm text-gray-500">'),
    line(2, 'Nenhuma conferência de estoque registrada ainda.'),
    line(1, '</div>'),
    line(0, ') : ('),
    line(1, '<div className="space-y-4">'),
    line(2, '<div className="space-y-4 border-b border-gray-100 pb-4">'),
    line(3, '<div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">'),
    line(4, '<div className="flex items-center gap-2 text-sm text-gray-600">'),
    line(5, '<Filter size={16} className="text-gray-400" />'),
    line(5, '<span className="font-semibold text-gray-700">Filtrar conferências</span>'),
    line(4, '</div>'),
    line(4, '<div className="text-xs text-gray-500">'),
    line(5, 'Mostrando {filteredStockConferenceHistory.length} de {stockConferenceHistory.length} conferência(s)'),
    line(4, '</div>'),
    line(3, '</div>'),
    line(3, '<div className="space-y-2">'),
    line(4, '<div className="text-[10px] uppercase tracking-widest text-gray-400">Filiais</div>'),
    line(4, '<div className="flex flex-wrap gap-2">'),
    line(5, '{stockConferenceBranches.map(branch => ('),
    line(6, '<button'),
    line(7, 'type="button"'),
    line(7, 'onClick={() => toggleStockBranchFilter(branch)}'),
    line(7, 'className={px-3 py-1.5 rounded-full text-xs font-semibold border transition }'),
    line(6, '>'),
    line(7, '{branch}'),
    line(5, '))}'),
    line(5, '{stockBranchFilters.length > 0 && ('),
    line(6, '<button'),
    line(7, 'type="button"'),
    line(7, 'onClick={handleResetStockBranchFilters}'),
    line(7, 'className="px-3 py-1.5 rounded-full border border-gray-200 bg-white text-xs text-gray-500 hover:bg-gray-50 transition"'),
    line(6, '>Limpar</button>'),
    line(5, ')}'),
    line(4, '</div>'),
    line(3, '</div>'),
    line(3, '<div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">'),
    line(4, '<span className="text-[10px] uppercase tracking-widest text-gray-400">Área</span>'),
    line(4, '<select'),
    line(5, 'value={stockAreaFilter}'),
    line(5, 'onChange={(e) => handleStockAreaFilterChange(e.target.value)}'),
    line(5, 'className="ml-0 w-full max-w-xs text-sm rounded-xl border border-gray-200 bg-white px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"'),
    line(4, '>'),
    line(5, '<option value="all">Todas as áreas</option>'),
    line(5, '{stockConferenceAreas.map(area => ('),
    line(6, '<option key={area} value={area}>{area}</option>'),
    line(5, '))}'),
    line(4, '</select>'),
    line(3, '</div>'),
    line(2, '</div>'),
    line(2, '{filteredStockConferenceHistory.length === 0 ? ('),
    line(3, '<div className="text-center py-12 text-sm text-gray-500">'),
    line(4, 'Nenhuma conferência de estoque encontrada com os filtros aplicados.'),
    line(3, '</div>'),
    line(2, ') : ('),
    line(3, '<div className="space-y-4">'),
    line(4, '{filteredStockConferenceHistory.map(item => {'),
    line(5, 'const createdDate = new Date(item.createdAt);'),
    line(5, 'return ('),
    line(6, '<div key={item.id} className="border border-gray-100 rounded-2xl p-4 shadow-sm bg-white">'),
    line(7, '<div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3">'),
    line(8, '<div>'),
    line(9, '<p className="text-xs uppercase tracking-widest text-gray-400">Filial</p>'),
    line(9, '<p className="text-base font-bold text-gray-800">{item.branch}</p>'),
    line(9, '<p className="text-sm text-gray-600 mt-1">Área: {item.area}</p>'),
    line(9, '<p className="text-xs text-gray-500 mt-1">'),
    line(10, '{createdDate.toLocaleDateString(\'pt-BR\', { day: \'2-digit\', month: \'short\', year: \'numeric\' })} às {createdDate.toLocaleTimeString(\'pt-BR\', { hour: \'2-digit\', minute: \'2-digit\' })}'),
    line(9, '</p>'),
    line(8, '</div>'),
    line(8, '<div className="bg-emerald-50 text-emerald-700 px-3 py-1 rounded-full text-[11px] font-bold">'),
    line(9, '{Math.round(item.percent)}% concluído'),
    line(8, '</div>'),
    line(7, '</div>'),
    line(7, '<div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-3 text-center text-sm">'),
    line(8, '<div className="bg-gray-50 rounded-xl py-3 border border-gray-100">'),
    line(9, '<p className="text-[10px] uppercase text-gray-400">Total</p>'),
    line(9, '<p className="text-lg font-bold text-gray-800">{item.total}</p>'),
    line(8, '</div>'),
    line(8, '<div className="bg-green-50 rounded-xl py-3 border border-green-100">'),
    line(9, '<p className="text-[10px] uppercase text-green-500">Corretos</p>'),
    line(9, '<p className="text-lg font-bold text-green-700">{item.matched}</p>'),
    line(8, '</div>'),
    line(8, '<div className="bg-red-50 rounded-xl py-3 border border-red-100">'),
    line(9, '<p className="text-[10px] uppercase text-red-500">Divergentes</p>'),
    line(9, '<p className="text-lg font-bold text-red-600">{item.divergent}</p>'),
    line(8, '</div>'),
    line(8, '<div className="bg-yellow-50 rounded-xl py-3 border border-yellow-100">'),
    line(9, '<p className="text-[10px] uppercase text-yellow-600">Pendente</p>'),
    line(9, '<p className="text-lg font-bold text-yellow-700">{item.pending}</p>'),
    line(8, '</div>'),
    line(7, '</div>'),
    line(7, '<div className="mt-4 flex flex-wrap gap-2 text-[11px] text-gray-500">'),
    line(8, '<span className="px-2 py-1 rounded-full bg-gray-100 border border-gray-200">Responsável: {item.userName}</span>'),
    line(8, '<span className="px-2 py-1 rounded-full bg-gray-100 border border-gray-200">Farmacêutico: {item.pharmacist}</span>'),
    line(8, '<span className="px-2 py-1 rounded-full bg-gray-100 border border-gray-200">Gestor: {item.manager}</span>'),
    line(7, '</div>'),
    line(7, '<div className="mt-4 flex justify-end">'),
    line(8, '<button'),
    line(9, 'onClick={() => handleViewStockConferenceReport(item.id)}'),
    line(9, 'className="flex items-center gap-2 rounded-2xl px-4 py-2 bg-blue-600 text-white text-sm font-bold shadow-lg hover:bg-blue-700 transition"'),
    line(8, '>'),
    line(9, '<FileText size={16} />'),
    line(9, 'Ver Conferência'),
    line(8, '</button>'),
    line(7, '</div>'),
    line(6, '</div>'),
    line(5, ');'),
    line(4, '} )}'),
    line(3, '</div>'),
    line(2, ') }'),
    line(1, '</div>'),
    line(0, ') }'),
]

new_block = "\n" + "\n".join(lines) + "\n"

path = Path('App.tsx')
text = path.read_text(encoding='latin-1')
start = text.index('                                {stockConferenceHistory.length === 0 ? (')
end = text.index('\n                            </div>', start)
text = text[:start] + new_block + text[end:]
path.write_text(text, encoding='latin-1')
